### ISSUE TITLE
About gazebo API

### ISSUE THREAD

**Issue by Guptajakala** [jsbruglie/gap#39]
Your code is awesome but I wonder where did you find the API about "gazebo::msgs::Visual"?

**Comment by joao-borrego** [comment]
Thank you! 

The contents of the Visual message are documented [here](http://osrf-distributions.s3.amazonaws.com/gazebo/msg-api/9.0.0/visual_8proto.html), although `.proto` are not really supported by Doxygen, so usually looking directly at the [code](https://bitbucket.org/osrf/gazebo/src/f4e51e8f64001beda70615ab8982a7d5a4e65b18/gazebo/msgs/visual.proto?at=default&fileviewer=file-view-default) is usually more helpful. It doesn't really tell you which functions are implemented for adding or removing fields, but it is standard across Protobuf messages.

If instead you mean where did I find out that Gazebo listens to `~/visual` topic and what it does with these messages, I'd say I was looking at the source and found [this](https://bitbucket.org/osrf/gazebo/src/f4e51e8f64001beda70615ab8982a7d5a4e65b18/gazebo/rendering/Scene.cc?at=default&fileviewer=file-view-default), specifically the Scene::ProcessVisualMsg function.

**Comment by Guptajakala** [comment]
Thank you for your timely response! 
I found .proto file once but there is no member functions related. I only shows the member variables. I found you are using function [mutable_material()](https://github.com/jsbruglie/gap/blob/53cbe644355ea8f0c1cf58d0700c0e89900cb6b3/utils/DRInterface.cc#L262)
That's so brilliant and I wonder if there is any place to know other similar member functions?

**Comment by joao-borrego** [comment]
These functions are not exactly provided by Gazebo, but automatically generated by the Protobuf compiler from the `.proto` message. Essentially depending on the type of data field, you get different ways to change it. I think [this](https://developers.google.com/protocol-buffers/docs/reference/cpp-generated) may be useful to help understand which functions are created for different types of fields.
In any case, if you have compiled Gazebo from source you can see the generated `.pb.h` headers for each message type in the `build/gazebo/msgs` directory.

**Comment by Guptajakala** [comment]
Cooooooooool! This is great to know. Thanks!
